import React, { useState } from 'react';
import { LessonPlan } from '../types';
import { Copy, Check, ChevronDown, ChevronUp, Share2, Printer } from 'lucide-react';

interface ResultViewProps {
  lesson: LessonPlan;
  onReset: () => void;
}

export const ResultView: React.FC<ResultViewProps> = ({ lesson, onReset }) => {
  const [copied, setCopied] = useState(false);
  const [showAnswers, setShowAnswers] = useState(false);

  const handleCopy = () => {
    let text = `${lesson.topic}\n\nSummary:\n${lesson.summary}\n\n`;
    
    if (lesson.mcqs.length > 0) {
      text += `Multiple Choice Questions:\n`;
      lesson.mcqs.forEach((q, i) => {
        text += `${i + 1}. ${q.question}\n`;
        q.options.forEach((opt, j) => text += `   ${String.fromCharCode(65 + j)}. ${opt}\n`);
        text += `   Answer: ${q.correctAnswer}\n\n`;
      });
    }
    
    if (lesson.shortQuestions.length > 0) {
        text += `Short Questions:\n`;
        lesson.shortQuestions.forEach((q, i) => {
            text += `${i + 1}. ${q.question}\n   Answer: ${q.answerKey}\n\n`;
        });
    }

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-4xl mx-auto pb-20">
      
      {/* Header Actions */}
      <div className="flex justify-between items-center mb-6">
        <button onClick={onReset} className="text-gray-500 hover:text-gray-800 font-medium text-sm">
          &larr; Create Another
        </button>
        <div className="flex gap-2">
          <button 
            onClick={handleCopy}
            className={`px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors ${copied ? 'bg-green-100 text-green-700' : 'bg-white text-gray-700 border border-gray-300 hover:bg-gray-50'}`}
          >
            {copied ? <Check size={18} /> : <Copy size={18} />}
            {copied ? 'Copied' : 'Copy Text'}
          </button>
           <button 
            className="px-4 py-2 rounded-lg font-medium flex items-center gap-2 bg-blue-600 text-white hover:bg-blue-700 shadow-sm"
          >
            <Printer size={18} />
            Print
          </button>
        </div>
      </div>

      {/* Lesson Content */}
      <div className="bg-white rounded-2xl shadow-xl overflow-hidden print:shadow-none">
        {/* Topic Header */}
        <div className="bg-blue-600 p-8 text-white">
          <h1 className="text-3xl font-bold mb-2">{lesson.topic}</h1>
          <div className="inline-block bg-blue-500 bg-opacity-50 rounded-full px-3 py-1 text-sm font-medium">
            Generated by ClassLens
          </div>
        </div>

        {/* Summary Section */}
        <div className="p-8 border-b border-gray-100">
          <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
            <span className="w-8 h-8 bg-purple-100 text-purple-600 rounded-full flex items-center justify-center text-sm">1</span>
            Explanation
          </h2>
          <div className="bg-purple-50 p-6 rounded-xl border border-purple-100 text-lg leading-relaxed text-gray-800">
            {lesson.summary}
          </div>
        </div>

        {/* MCQs Section */}
        {lesson.mcqs.length > 0 && (
          <div className="p-8 border-b border-gray-100">
             <h2 className="text-xl font-bold text-gray-800 mb-6 flex items-center gap-2">
                <span className="w-8 h-8 bg-blue-100 text-blue-600 rounded-full flex items-center justify-center text-sm">2</span>
                Multiple Choice
             </h2>
             <div className="grid gap-6">
               {lesson.mcqs.map((q, idx) => (
                 <div key={idx} className="bg-gray-50 p-5 rounded-xl border border-gray-200">
                   <p className="font-semibold text-gray-900 mb-3">{idx + 1}. {q.question}</p>
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                     {q.options.map((opt, oIdx) => (
                       <div key={oIdx} className="flex items-center gap-3 p-2 bg-white rounded border border-gray-200">
                         <span className="w-6 h-6 rounded-full bg-gray-100 text-gray-500 flex items-center justify-center text-xs font-bold">
                           {String.fromCharCode(65 + oIdx)}
                         </span>
                         <span className="text-gray-700">{opt}</span>
                       </div>
                     ))}
                   </div>
                   {showAnswers && (
                     <div className="mt-4 pt-3 border-t border-gray-200 text-green-700 font-medium flex items-start gap-2">
                       <Check size={18} className="mt-0.5" /> 
                       <div>
                        Correct: {q.correctAnswer}
                        {q.explanation && <p className="text-sm text-gray-600 font-normal mt-1">{q.explanation}</p>}
                       </div>
                     </div>
                   )}
                 </div>
               ))}
             </div>
          </div>
        )}

        {/* Short Answers Section */}
        {lesson.shortQuestions.length > 0 && (
          <div className="p-8 border-b border-gray-100">
             <h2 className="text-xl font-bold text-gray-800 mb-6 flex items-center gap-2">
                <span className="w-8 h-8 bg-orange-100 text-orange-600 rounded-full flex items-center justify-center text-sm">3</span>
                Short Questions
             </h2>
             <div className="space-y-4">
                {lesson.shortQuestions.map((q, idx) => (
                  <div key={idx} className="bg-white p-0">
                    <p className="font-medium text-gray-900 mb-2">{idx + 1}. {q.question}</p>
                    <div className="h-20 border-b-2 border-gray-200 border-dashed w-full"></div>
                     {showAnswers && (
                     <div className="mt-2 bg-orange-50 p-3 rounded-lg text-orange-800 text-sm">
                       <strong>Model Answer:</strong> {q.answerKey}
                     </div>
                   )}
                  </div>
                ))}
             </div>
          </div>
        )}

        {/* Fill in Blanks Section */}
        {lesson.fillInBlanks.length > 0 && (
          <div className="p-8 border-b border-gray-100">
             <h2 className="text-xl font-bold text-gray-800 mb-6 flex items-center gap-2">
                <span className="w-8 h-8 bg-teal-100 text-teal-600 rounded-full flex items-center justify-center text-sm">4</span>
                Fill in the Blanks
             </h2>
             <div className="space-y-4">
                {lesson.fillInBlanks.map((q, idx) => (
                  <div key={idx} className="bg-teal-50/50 p-4 rounded-lg">
                    <p className="font-medium text-gray-900">{idx + 1}. {q.sentence}</p>
                     {showAnswers && (
                     <div className="mt-2 text-teal-700 font-semibold text-sm">
                       Answer: {q.answer}
                     </div>
                   )}
                  </div>
                ))}
             </div>
          </div>
        )}

      </div>
      
      {/* Footer Toggle */}
      <div className="fixed bottom-0 left-0 w-full bg-white border-t border-gray-200 p-4 shadow-lg flex justify-center z-50">
        <button 
          onClick={() => setShowAnswers(!showAnswers)}
          className="bg-gray-900 text-white px-6 py-3 rounded-full font-semibold shadow-xl hover:bg-gray-800 transition-transform active:scale-95 flex items-center gap-2"
        >
          {showAnswers ? <ChevronDown size={20} /> : <ChevronUp size={20} />}
          {showAnswers ? 'Hide Answers' : 'Show Answers Key'}
        </button>
      </div>

    </div>
  );
};